name: publish-to-git

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ./
        id: publish
        with:
          branch: master
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          source_folder: .github
          target_folder: test
          dry_run: true
      - shell: bash
        run: |
          test -n "${{ steps.publish.outputs.commit_hash }}"
          test -n "${{ steps.publish.outputs.working_directory }}"

